/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  New_Basic_Mouse2                       */
/*      FILE         :  sbrk.h                                 */
/*      DESCRIPTION  :  Header file of sbrk file               */
/*      CPU SERIES   :  RX200                                  */
/*      CPU TYPE     :  RX220                                  */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/

/* size of area managed by sbrk */
#define HEAPSIZE 0x400